<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Bestfriends six.</title>
    <link rel="stylesheet" href="style.css">
    <P>CERLI +62 815-4976-2298</P>
    <P>JULI +62 856-9449-5237</P>
    <P>ECE +62 823-5073-3505</P>
    <P>ECA +62 812-5310-5626</P>
    <P>NONG +62 813-8194-5577</P>
    <li><a href="sedekah.php" class="tbl-biru">HOME</a></li>
</body>
</html>
